services:
  - type: web         # This is a web service that listens for HTTP traffic.
    name: virtual-ta  # The name for your service on Render.
    env: python       # The environment language.
    plan: free        # Use Render's free tier.
    
    # This tells Render to treat the 'api' folder as the root for commands.
    # This is CRUCIAL and simplifies everything.
    rootDir: ./api  
    
    # Build command: This runs once when you deploy.
    # Since rootDir is 'api', it correctly finds 'api/requirements.txt'.
    buildCommand: "pip install -r requirements.txt"
    
    # Start command: This runs continuously to keep your server online.
    # This is the most important command.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
